[package]
name = "append_tree"
version = "0.1.0"
authors = ["Austin Hicks <camlorn@camlorn.net>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
bincode = "0.8.0"
take_mut = "0.1.3"

[dev-dependencies]
rand = "0.3"
